//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videodetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoDetail
    {
        public int FileId { get; set; }
        public string Length { get; set; }
        public string FrameWidth { get; set; }
        public string FrameHeight { get; set; }
        public string CodecName { get; set; }
        public string CodecTag { get; set; }
        public string BitRate { get; set; }
        public string FrameRate { get; set; }
        public string CodecDescription { get; set; }
    }
}
